mysite/account/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path


from .views import (MyLogoutView,
                    RegisterView,
                    )


app_name = 'account'
urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='account/login.html',
             redirect_authenticated_user=True
         ), name='login'),
    path('logout/', MyLogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

mysite/recipe/urls.py
from django.urls import path

from .views import RecipeView, CreateRecipeView, DetailRecipeView, UpdateRecipeView

app_name = 'recipe'

urlpatterns = [
    path('', RecipeView.as_view(), name='index'),
    path('create_recipe/', CreateRecipeView.as_view(), name='create_recipe'),
    path('detail_recipe/<int:pk>/', DetailRecipeView.as_view(), name='detail_recipe'),
    path('update_recipe/<int:pk>/', UpdateRecipeView.as_view(), name='update_recipe'),
]

mysite/account/models.py
from django.db import models

mysite/recipe/models.py
from django.db import models
from django.contrib.auth.models import User


def create_path_to_upload_images(instance: 'Recipe', name: str) -> str:
    return f'images/{instance.category.name}/{name}'


class Recipe(models.Model):
    name = models.CharField(
        max_length=150, blank=False, null=False, unique=True, verbose_name='Название блюда')
    description = models.TextField(
        max_length=2000, blank=False, null=False, verbose_name='Описание блюда')
    steps = models.TextField(max_length=5000, blank=False, null=False, verbose_name='Шаги приготовления блюда')
    time = models.CharField(max_length=60, blank=False, null=False, verbose_name='Время приготовления блюда')
    image = models.ImageField(upload_to=create_path_to_upload_images, blank=False, null=False, verbose_name='Изображение блюда')
    author = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, default=1, related_name='recipes',
                               related_query_name='recipe')
    ingredients = models.TextField(max_length=2000, blank=False, null=False, verbose_name='Ингридиенты')
    category = models.ForeignKey(to='Category', on_delete=models.SET_NULL, null=True, related_name='recipes',
                                 related_query_name='recipe')
    date_create = models.DateField(auto_now_add=True, verbose_name='Дата добавления')

    def __str__(self):
        return self.name

    def get_short_description(self):
        if len(self.description) < 40:
            return self.description
        return f'{self.description[:40]}...'

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'


class Category(models.Model):
    name = models.CharField(max_length=150, blank=False, null=False, unique=True, verbose_name='Название категории', )
    description = models.TextField(max_length=1000, blank=False, null=False, verbose_name='Описание категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

mysite/account/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView


class MyLogoutView(LogoutView):
    next_page = reverse_lazy('recipe:index')


class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'account/register.html'

    def get_success_url(self):
        user = self.object
        login(self.request, user)
        return reverse('recipe:index')

mysite/recipe/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView

from .models import Recipe


class RecipeView(ListView):
    queryset = Recipe.objects.order_by('?').select_related('category')[:5]
    template_name = 'recipe/index.html'


class CreateRecipeView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'recipe/create_recipe.html'
    fields = 'name', 'description', 'time', 'steps', 'image', 'ingredients', 'category'
    success_url = reverse_lazy('recipe:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdateRecipeView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Recipe
    template_name = 'recipe/update_recipe.html'
    fields = 'name', 'description', 'time', 'steps', 'image', 'ingredients', 'category'
    success_url = reverse_lazy('recipe:index')

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author or self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('recipe:index')

class DetailRecipeView(DetailView):
    queryset = Recipe.objects.select_related('category')
    template_name = 'recipe/detail_recipe.html'

mysite/recipe/templates/recipe/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
        body {
            background-color: #f7defb;
        }
        body a {
            font-size: 20px;
            text-decoration: none;
        }
        body a:hover {
            color: red; /* Цвет ссылки при наведении */
        }

        .auth {
            font-size: 20px;
        }

        .user_content {
            text-align: right;
            display: flex;
            justify-content: flex-end;
            gap: 15px;
        }
    </style>
    <title>
        {% block title %}
            Base Title
        {% endblock%}
    </title>
</head>
<body>
    <div class="user_content">
        {% if not user.is_authenticated %}
            <p class="auth">Вы не авторизованы</p>
        {% else %}
            <p class="auth" >Авторизован {{ user }}</p>
        {% endif %}
        {% if user.is_staff %}
           <p class="auth"> <a href="{% url 'admin:index' %}">Админ-панель</a></p>
        {% endif %}

        {% if not user.is_authenticated %}
           <p class="auth"> <a href="{% url 'account:login' %}">Вход</a></p>
           <p class="auth"> <a href="{% url 'account:register' %}">Регистрация</a></p>
        {% else %}
           <p class="auth"> <a href="{% url 'account:logout' %}">Выход</a></p>
        {% endif %}
    </div>
    {% block body %}
        <h1>Base body</h1>
    {% endblock%}
</body>
</html>

mysite/recipe/templates/recipe/create_recipe.html
{% extends 'recipe/base.html'%}

   {% block title %}
        Добавление рецепта
   {% endblock %}

   {% block body %}
<style>
    .recipe-form {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f9f9f98f;
        box-shadow: 7px -2px 10px rgb(0 0 0 / 32%);
    }

    h1 {
        text-align: center;
        color: #333;
    }
    h2 {
        text-align: center;
        color: #333;
    }

    .recipe-form label {
        font-weight: bold;
        margin-top: 10px;
        display: block;
    }

    .recipe-form input[type="text"],
    .recipe-form textarea,
    .recipe-form select {
        width: 97%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 15px;
        font-size: 16px;
    }

    .recipe-form input[type="file"] {
        margin-top: 5px;
    }

    .btn-submit {
        border: inherit;
        background-color: #f7defb;
        border-radius: 15px;
        width: 97%;
        height: 35px;
        font-size: 15px;
        font-weight: bold;
    }

    .btn-submit:hover {
        background-color: #f3a8ff;
    }

    .btn-back {
        display: inline-block;
        margin-top: 15px;
        text-decoration: none;
        color: #007BFF;
        font-weight: bold;
    }

    .btn-back:hover {
        text-decoration: underline; /* Подчеркивание при наведении */
    }
</style>
            <form class="recipe-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-submit">Сохранить</button>
            </form>

   {% endblock %}

mysite/recipe/templates/recipe/detail_recipe.html
{% extends 'recipe/base.html'%}

    {% block title %}
        Подробнее
    {% endblock%}

    {% block body %}
        <style>
            .recipe {
                display: flex;
                flex-direction: column;
                align-items: center;
            }
            .title_recipe {
                text-align: center;
            }

            .recipe_content {
                max-width: 675px;
            }

            .actions {
                display: flex;
                justify-content: space-between;
            }

        </style>
        <div class="recipe">
            <div class="title_recipe">
                <h1>{{ object }}</h1>
                <img style="width:400px" src="{{ object.image.url }}" alt="{{ object.image.name }}">
            </div>

            <div class="recipe_content">
                <h3>Описание:</h3>
                <p>{{ object.description }}</p>

                <h3>Шаги приготовления:</h3>
                <p>{{ object.steps }}</p>

                <h3>Время приготовления:</h3>
                <p>{{ object.time }}</p>

                <h3>Автор рецепта:</h3>
                <p>{{ object.author.username }}</p>

                <h3>Ингридиенты:</h3>
                <p>{{ object.ingredients }}</p>

                <h3>Категория:</h3>
                <p>{{ object.category }}</p>

                <h3>Добавлен:</h3>
                <p>{{ object.date_create }}</p>
                <div class="actions">
                    <p><a href="{% url 'recipe:index' %}">Назад к списку рецептов</a></p>
                    {% if user == object.author %}
                    <p><a href="{% url 'recipe:update_recipe' pk=object.pk %}">Изменить рецепт</a></p>
                    {% endif %}
                </div>
            </div>

        </div>

    {% endblock %}

mysite/recipe/templates/recipe/index.html
{% extends 'recipe/base.html'%}

    {% block title %}
        Сайт рецептов
    {% endblock%}

    {% block body %}
        <h1>Список рецептов</h1>
        <ol>
            {% for recipe in object_list %}
                <div>
                    <li>
                        <a href="{% url 'recipe:detail_recipe' pk=recipe.pk %}">{{ recipe.name }}</a>
                        <ul>
                            <img style="width: 300px" src="{{ recipe.image.url }}" alt="{{ recipe.image.name }}">
                            <li>{{ recipe.get_short_description }}</li>
                            <li><p>Время приготовления: {{ recipe.time }}</p></li>
                            <li><p>Автор рецепта: {{ recipe.author }}</p></li>
                            <li><p>Категория: {{ recipe.category }}</p></li>
                            <li><p>Дата добавления: {{ recipe.date_create }}</p></li>
                        </ul>
                    </li>
                </div><br>
            {% empty %}
                <p>Еще нет ни одного рецепта...</p>
            {% endfor %}
        </ol>

        <a href="{% url 'recipe:create_recipe' %}">Добавить рецепт</a>

    {% endblock%}

mysite/recipe/templates/recipe/update_recipe.html
{% extends 'recipe/base.html'%}

   {% block title %}
        Редактирование рецепта
   {% endblock %}

   {% block body %}
<style>
    .recipe-form {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 10px;
        background-color: #f9f9f98f;
        box-shadow: 7px -2px 10px rgb(0 0 0 / 32%);
    }

    h1 {
        text-align: center;
        color: #333;
    }
    h2 {
        text-align: center;
        color: #333;
    }

    .recipe-form label {
        font-weight: bold;
        margin-top: 10px;
        display: block;
    }

    .recipe-form input[type="text"],
    .recipe-form textarea,
    .recipe-form select {
        width: 97%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 15px;
        font-size: 16px;
    }

    .recipe-form input[type="file"] {
        margin-top: 5px;
    }

    .btn-submit {
        border: inherit;
        background-color: #f7defb;
        border-radius: 15px;
        width: 97%;
        height: 35px;
        font-size: 15px;
        font-weight: bold;
    }

    .btn-submit:hover {
        background-color: #f3a8ff;
    }

    .btn-back {
        display: inline-block;
        margin-top: 15px;
        text-decoration: none;
        color: #007BFF;
        font-weight: bold;
    }

    .btn-back:hover {
        text-decoration: underline; /* Подчеркивание при наведении */
    }
</style>
            <form class="recipe-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn-submit">Сохранить</button>
            </form>

   {% endblock %}